variable "vpc_cidr_blocks" {}
variable "env_prefix" {}
variable "subnet_cidr_blocks" {}
variable "availability_zone" {}
variable "public_ip" {}
#variable "public_key_data" {}
variable "instance_type" {}
variable "region" {}
variable "private_key_location" {}